### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by robmarkcole** [Bishma/home-assistant-tng#1]
HI
I've been working on a project which may be of interest. My long term goal is to get more people gathering their own data. Let me know if its of interest.
Cheers

https://github.com/robmarkcole/HASS-circuitpython-air-quality-sensor-node

**Comment by Bishma** [comment]
Thank you for passing that along. I'm just dipping my toes into the homebrew microelectronic scene and this looks like a valuable project to help give me some experience.
